Implement new traits for `<iterator>`
NVIDIA/libcudacxx pull request #489
Opened 2023-06-21 14:51 UTC by miscco

This implements the updates to iterator_traits as well as the new readable_traits and incrementable_traits. It further adds the related iter_value_t and iter_difference_t aliases

2023-06-23 18:59 UTC, ericniebler requested changes
minor nits only

2023-07-03 07:28 UTC, miscco commented on .upstream-tests/test/support/iterator_traits_cpp17_iterators.h
> +};
Ditto, this is an artifact from me trying to break things up into "small" commits

2023-07-03 07:28 UTC, miscco commented on .upstream-tests/test/support/iterator_traits_cpp17_iterators.h
> +};
That is an artifact of me trying to break everything into small pieces. The iterators get fully upgraded when we actually merge the interator concepts commit, which comes 4 commits later.

2023-07-03 07:28 UTC, miscco commented on .upstream-tests/test/support/iterator_traits_cpp17_iterators.h
> +  // this returns legcay_iterator, not iterator_traits_cpp17_proxy_iterator
Ditto

2023-07-05 23:41 UTC, ericniebler commented on .upstream-tests/test/std/iterators/iterator.requirements/iterator.assoc.types/readable.traits/iter_value_t.pass.cpp
> +static_assert(check_no_iter_value_t<different_value_element_members>());
*\<bump>*

2023-07-06 06:10 UTC, miscco commented
Closing as this has been mirrored to https://github.com/NVIDIA/cccl/pull/158

2023-07-06 06:10 UTC, closed without merging